# Generated by Django 5.2.6 on 2025-11-04 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EspeciePlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('nombre_cientifico', models.CharField(blank=True, max_length=150, null=True)),
                ('familia', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('referencia_url', models.URLField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Especie de Planta',
                'verbose_name_plural': 'Especies de Plantas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MiPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apodo', models.CharField(blank=True, help_text='Nombre personalizado para identificar este ejemplar', max_length=100, null=True)),
                ('ubicacion', models.CharField(blank=True, help_text='Dónde está ubicada (ej: cocina, balcón)', max_length=100, null=True)),
                ('estado', models.IntegerField(choices=[(0, 'Enferma'), (1, 'Saludable'), (2, 'Crítica')], default=1)),
                ('porcentaje_verde', models.FloatField(default=0.0)),
                ('porcentaje_amarillo', models.FloatField(default=0.0)),
                ('porcentaje_marron', models.FloatField(default=0.0)),
                ('porcentaje_rojo', models.FloatField(default=0.0)),
                ('descripcion_estado', models.TextField(blank=True, null=True)),
                ('fecha_agregada', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejemplares', to='clasificador.especieplanta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_plantas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mi Planta',
                'verbose_name_plural': 'Mis Plantas',
                'ordering': ['-ultima_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='MonitoreoPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(choices=[(0, 'Enferma'), (1, 'Saludable'), (2, 'Crítica')])),
                ('porcentaje_verde', models.FloatField()),
                ('porcentaje_amarillo', models.FloatField()),
                ('porcentaje_marron', models.FloatField()),
                ('porcentaje_rojo', models.FloatField()),
                ('descripcion_estado', models.TextField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, help_text='Observaciones adicionales del usuario', null=True)),
                ('foto_url', models.URLField(blank=True, help_text='URL de foto capturada en este monitoreo', null=True)),
                ('fecha_monitoreo', models.DateTimeField(auto_now_add=True)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoreos', to='clasificador.miplanta')),
            ],
            options={
                'verbose_name': 'Monitoreo',
                'verbose_name_plural': 'Monitoreos',
                'ordering': ['-fecha_monitoreo'],
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_cientifico', models.CharField(blank=True, max_length=150, null=True)),
                ('familia', models.CharField(blank=True, max_length=100, null=True)),
                ('Descripcion', models.TextField(blank=True, null=True)),
                ('ImagenURL', models.URLField(blank=True, null=True)),
                ('Estado', models.IntegerField(default=1)),
                ('porcentaje_verde', models.FloatField(default=0.0)),
                ('porcentaje_amarillo', models.FloatField(default=0.0)),
                ('porcentaje_marron', models.FloatField(default=0.0)),
                ('porcentaje_rojo', models.FloatField(default=0.0)),
                ('descripcion_estado', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
