# Generated by Django 5.2.6 on 2025-11-05 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasificador', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miplanta',
            name='apodo',
        ),
        migrations.RemoveField(
            model_name='miplanta',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='especieplanta',
            name='agregada_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que sugirió esta especie', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='especieplanta',
            name='en_modelo_entrenado',
            field=models.BooleanField(default=False, help_text='True si está en el modelo CNN actual'),
        ),
        migrations.AddField(
            model_name='especieplanta',
            name='pendiente_entrenamiento',
            field=models.BooleanField(default=False, help_text='True si fue detectada pero no está en el modelo'),
        ),
        migrations.AddField(
            model_name='especieplanta',
            name='total_ejemplares',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monitoreoplanta',
            name='foto_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitoreoplanta',
            name='notas',
            field=models.TextField(blank=True, help_text='Tus observaciones en este monitoreo', null=True),
        ),
        migrations.DeleteModel(
            name='Planta',
        ),
    ]
