# Generated by Django 5.2.6 on 2025-11-08 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasificador', '0002_remove_miplanta_apodo_remove_miplanta_ubicacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsejoCuidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luz', models.TextField(help_text='Requerimientos de iluminación', verbose_name='Luz')),
                ('riego', models.TextField(help_text='Frecuencia y método de riego', verbose_name='Riego')),
                ('temperatura', models.CharField(help_text='Rango de temperatura ideal', max_length=100, verbose_name='Temperatura')),
                ('humedad', models.CharField(help_text='Nivel de humedad requerido', max_length=100, verbose_name='Humedad')),
                ('suelo', models.TextField(help_text='Tipo de sustrato recomendado', verbose_name='Suelo')),
                ('fertilizacion', models.TextField(help_text='Frecuencia y tipo de fertilizante', verbose_name='Fertilización')),
                ('poda', models.TextField(blank=True, help_text='Instrucciones de poda (opcional)', null=True, verbose_name='Poda')),
                ('plagas_comunes', models.TextField(blank=True, help_text='Plagas y enfermedades frecuentes (opcional)', null=True, verbose_name='Plagas comunes')),
                ('toxicidad', models.CharField(choices=[('no_toxica', 'No tóxica'), ('toxica_leve', 'Levemente tóxica'), ('toxica', 'Tóxica'), ('muy_toxica', 'Muy tóxica')], default='no_toxica', help_text='Nivel de toxicidad para mascotas/humanos', max_length=50)),
                ('dificultad', models.CharField(choices=[('facil', 'Fácil'), ('moderada', 'Moderada'), ('dificil', 'Difícil')], default='moderada', help_text='Nivel de dificultad de cuidado', max_length=20)),
                ('notas_adicionales', models.TextField(blank=True, help_text='Información extra útil (opcional)', null=True, verbose_name='Notas adicionales')),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar para ocultar estos consejos temporalmente')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('especie', models.OneToOneField(help_text='Especie a la que pertenecen estos consejos', on_delete=django.db.models.deletion.CASCADE, related_name='consejo', to='clasificador.especieplanta')),
            ],
            options={
                'verbose_name': 'Consejo de Cuidado',
                'verbose_name_plural': 'Consejos de Cuidado',
                'ordering': ['especie__nombre'],
                'permissions': [('view_all_consejos', 'Puede ver todos los consejos')],
            },
        ),
    ]
