# Generated by Django 5.2.6 on 2025-11-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasificador', '0003_consejocuidado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoreoplanta',
            name='foto_url',
        ),
        migrations.AddField(
            model_name='monitoreoplanta',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='monitoreos/'),
        ),
    ]
