# Generated by Django 5.2.6 on 2025-11-10 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clasificador', '0004_remove_monitoreoplanta_foto_url_monitoreoplanta_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoreoplanta',
            name='foto',
        ),
    ]
