# Generated by Django 5.2.6 on 2025-11-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasificador', '0005_remove_monitoreoplanta_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='miplanta',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen capturada en este monitoreo', null=True, upload_to='monitoreos/'),
        ),
    ]
