# Generated by Django 5.2.6 on 2025-11-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasificador', '0006_miplanta_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miplanta',
            name='imagen',
        ),
        migrations.AddField(
            model_name='monitoreoplanta',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen capturada en este monitoreo', null=True, upload_to='monitoreos/'),
        ),
    ]
