# Generated by Django 5.2.6 on 2025-11-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasificador', '0007_remove_miplanta_imagen_monitoreoplanta_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoreoplanta',
            name='imagen',
        ),
        migrations.AddField(
            model_name='monitoreoplanta',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='monitoreos/'),
        ),
    ]
