# Generated by Django 5.2.6 on 2025-11-10 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clasificador', '0009_remove_monitoreoplanta_foto_framecapturado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrameCapturado',
        ),
    ]
