# Generated by Django 5.2.6 on 2025-11-10 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasificador', '0010_delete_framecapturado'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameCapturado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='frames/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monitoreo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clasificador.monitoreoplanta')),
            ],
        ),
    ]
