# Generated by Django 5.2.6 on 2025-11-10 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasificador', '0011_framecapturado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='framecapturado',
            options={'ordering': ['-fecha'], 'verbose_name': 'Frame Capturado', 'verbose_name_plural': 'Frames Capturados'},
        ),
        migrations.AlterField(
            model_name='framecapturado',
            name='imagen',
            field=models.ImageField(upload_to='frames/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='framecapturado',
            name='monitoreo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='clasificador.monitoreoplanta'),
        ),
    ]
