# Generated by Django 5.2.6 on 2025-11-10 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clasificador', '0012_alter_framecapturado_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrameCapturado',
        ),
    ]
